print("Arethmetic Progration Problem...")
a=int(input("First term:"))
d=int(input("Comman Diffrence:"))
n=int(input("No. of terms :"))
An=(a+(n-1)*d)
Sn=(n/2*(2*a+(n-1)*d))
print("Last term:",An)
print("Sum of all terms:",Sn)