def line():
    print("================================================================================")
print("Heloo User...")
name=input("Enter Name:")
print("Hello",name)
line()
age=int(input("Age:"))
line()
phone=int(input("Phone No :"))
line()
print("Thank You...")
line()
