print("Hello Users...")
a=input("Please Enter Name:")
print("Hello",a)
print("Welcome to our Web page \n We will try to make your work easy...")
print("Please Enter Details below...")
A=input("Name :")
B=int(input("Enter Contact Info.. \n  Mobile No :"))
C=input("E-Mail ID :")
D=input("The Previous Place where you did Job : ")
print("You had worked at nice place..")
E=input("Which type of job you need :")
F=int(input("The working month in previous Job:"))
print("Thank You for giving your details \n Our team will contact you shortly.")