print(" Welcome to Vaibhav fashion store.")
name=input("Enter Full Name:")
info=int(input("Enter Phone No. :"))
eid=input("Enter EMAIL-ID:")
op=int(input("Age in years :",))
a=int(input("No. of item you bought:"))
if(a==1):
    print("Mode of payments are\n[PhonePe, Paytm,GooglePay,BHIM,Cash,Samsung Pay or Bank UIP ]")
    b=input("Mode of Payment:")
    a11=input("Enter the name of Item:")
    a1=float(input("Cost of Item:"))
    print("Total amount: Rs",a1)
    print("The mode of payment is :",b)
    print("Thank You",name," to bought item from us")
elif(a==2):
    a21=input("Enter the name of Item 1:")
    a2=float(input("Cost of Item 1:"))
    a22=input("Enter the name of Item 2:")
    a2a=float(input("Cost of Item 2:"))
    A1=a2+a2a
    print("Total amount: Rs",A1)
    print("The mode of payment is :",b)
    print("Thank You",name," to bought item from us")
elif(a==3):
     a31=input("Enter the name of Item 1:")
     a3=float(input("Cost of Item 1:"))
     a32=input("Enter the name of Item 2:")
     a3a=float(input("Cost of Item 2:"))
     a33=input("Enter the name of Item 3:")
     a3b=float(input("Cost of Item 3:"))
     A2=a3+a3a+a3b
     print("Total amount: Rs",A2)
     print("The mode of payment is :",b)
     print("Thank You",name," to bought item from us")
elif(a==4):
     a41=input("Enter the name of Item 1:")
     a4=float(input("Cost of Item 1:"))
     a42=input("Enter the name of Item 2:")
     a4a=float(input("Cost of Item 2:"))
     a43=input("Enter the name of Item 3:")
     a4b=float(input("Cost of Item 3:"))
     a44=input("Enter the name of Item 4:")
     a4c=float(input("Cost of Item 4:"))
     A3=a4+a4a+a4b+a4c
     print("Total amount: Rs",A3)
     print("The mode of payment is :",b)
     print("Thank You",name," to bought item from us")
elif(a==5):
     a51=input("Enter the name of Item 1:")
     a5=float(input("Cost of Item 1:"))
     a52=input("Enter the name of Item 2:")
     a5a=float(input("Cost of Item 2:"))
     a53=input("Enter the name of Item 3:")
     a5b=float(input("Cost of Item 3:"))
     a54=input("Enter the name of Item 4:")
     a5c=float(input("Cost of Item 4:"))
     a55=input("Enter the name of Item 5:")
     a5d=float(input("Cost of Item 5:"))
     A4=a5+a5a+a5b+a5c+a5d
     print("Total amount: Rs",A4)
     print("The mode of payment is :",b)
     print("Thank You",name," to bought item from us")
elif(a==6):
     a61=input("Enter the name of Item 1:")
     a6=float(input("Cost of Item 1:"))
     a62=input("Enter the name of Item 2:")
     a6a=float(input("Cost of Item 2:"))
     a63=input("Enter the name of Item 3:")
     a6b=float(input("Cost of Item 3:"))
     a64=input("Enter the name of Item 4:")
     a6c=float(input("Cost of Item 4:"))
     a65=input("Enter the name of Item 5:")
     a6d=float(input("Cost of Item 5:"))
     a66=input("Enter the name of Item 6:")
     a6e=float(input("Cost of Item 6:"))
     A5=a+a6a+a6b+a6c+a6d+a6e
     print("Total amount: Rs",A5)
     print("The mode of payment is :",b)
     print("Thank You",name," to bought item from us")
elif(a==7):
     a71=input("Enter the name of Item 1:")
     a7=float(input("Cost of Item 1:"))
     a72=input("Enter the name of Item 2:")
     a7a=float(input("Cost of Item 2:"))
     a73=input("Enter the name of Item 3:")
     a7b=float(input("Cost of Item 3:"))
     a74=input("Enter the name of Item 4:")
     a7c=float(input("Cost of Item 4:"))
     a75=input("Enter the name of Item 5:")
     a7d=float(input("Cost of Item 5:"))
     a76=input("Enter the name of Item 6:")
     a7e=float(input("Cost of Item 6:"))
     a77=input("Enter the name of Item 7:")
     a7f=float(input("Cost of Item 7:"))
     A6=a7+a7a+a7b+a7c+a7d+a7e+a7f
     print("Total amount: Rs",A6)
     print("The mode of payment is :",b)
     print("Thank You",name," to bought item from us")
elif(a==8):
     a81=input("Enter the name of Item 1:")
     a8=float(input("Cost of Item 1:"))
     a82=input("Enter the name of Item 2:")
     a8a=float(input("Cost of Item 2:"))
     a83=input("Enter the name of Item 3:")
     a8b=float(input("Cost of Item 3:"))
     a84=input("Enter the name of Item 4:")
     a8c=float(input("Cost of Item 4:"))
     a85=input("Enter the name of Item 5:")
     a8d=float(input("Cost of Item 5:"))
     a86=input("Enter the name of Item 6:")
     a8e=float(input("Cost of Item 6:"))
     a87=input("Enter the name of Item 7:")
     a8f=float(input("Cost of Item 7:"))
     a88=input("Enter the name of Item 8:")
     a8g=float(input("Cost of Item 8:"))
     A7=a8+a8a+a8b+a8c+a8d+a8e+a8f+a8g
     print("Total amount: Rs",A7)
     print("The mode of payment is :",b)
     print("Thank You",name," to bought item from us")
elif(a==9):
     a91=input("Enter the name of Item 1:")
     a9=float(input("Cost of Item 1:"))
     a92=input("Enter the name of Item 2:")
     a9a=float(input("Cost of Item 2:"))
     a93=input("Enter the name of Item 3:")
     a9b=float(input("Cost of Item 3:"))
     a94=input("Enter the name of Item 4:")
     a9c=float(input("Cost of Item 4:"))
     a95=input("Enter the name of Item 5:")
     a9d=float(input("Cost of Item 5:"))
     a96=input("Enter the name of Item 6:")
     a9e=float(input("Cost of Item 6:"))
     a97=input("Enter the name of Item 7:")
     a9f=float(input("Cost of Item 7:"))
     a98=input("Enter the name of Item 8:")
     a9g=float(input("Cost of Item 8:"))
     a99=input("Enter the name of Item 9:")
     a9h=float(input("Cost of Item 9:"))
     A8=a9+a9a+a9b+a9c+a9d+a9e+a9f+a9g+a9h
     print("Total amount: Rs",A8)
     print("The mode of payment is :",b)
     print("Thank You",name," to bought item from us")
elif(a==10):
     a101=input("Enter the name of Item 1:")
     a10=float(input("Cost of Item 1:"))
     a102=input("Enter the name of Item 2:")
     a10a=float(input("Cost of Item 2:"))
     a103=input("Enter the name of Item 3:")
     a10b=float(input("Cost of Item 3:"))
     a104=input("Enter the name of Item 4:")
     a10c=float(input("Cost of Item 4:"))
     a105=input("Enter the name of Item 5:")
     a10d=float(input("Cost of Item 5:"))
     a106=input("Enter the name of Item 6:")
     a10e=float(input("Cost of Item 6:"))
     a107=input("Enter the name of Item 7:")
     a10f=float(input("Cost of Item 7:"))
     a108=input("Enter the name of Item 8:")
     a10g=float(input("Cost of Item 8:"))
     a109=input("Enter the name of Item 9:")
     a10h=float(input("Cost of Item 9:"))
     a1000=input("Enter the name of Item 10:")
     a10i=float(input("Cost of Item 10:"))
     A9=a10+a10a+a10b+a10c+a10d+a10e+a10f+a10g+a10h+a10i
     print("Total amount: Rs",A9)
     print("The mode of payment is :",b)
     print("Thank You",name," to bought item from us")
else:
    print("You can add 10 items at a time. \nThank you.")
    print("You can make the bill two times for more than 10 items")
